all: W:\Algorithms-Data-Structures-and-Programming-Challenges\Bit-Manipulation\CPROG_setbits.c
    @echo Building W:\Algorithms-Data-Structures-and-Programming-Challenges\Bit-Manipulation\CPROG_setbits.c
    gcc -o -Wall W:\Algorithms-Data-Structures-and-Programming-Challenges\Bit-Manipulation\CPROG_setbits.c main.c
clean:
    @echo Cleaning up
    rm -f W:\Algorithms-Data-Structures-and-Programming-Challenges\Bit-Manipulation\CPROG_setbits.c
    @echo Done
run:
    @echo Running W:\Algorithms-Data-Structures-and-Programming-Challenges\Bit-Manipulation\CPROG_setbits.c
    ./W:\Algorithms-Data-Structures-and-Programming-Challenges\Bit-Manipulation\CPROG_setbits.c

